FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /profiler-server ./cmd/server

FROM alpine:3.19

RUN apk add --no-cache docker-cli

WORKDIR /app

COPY --from=builder /profiler-server /app/profiler-server

EXPOSE 50051

CMD ["/app/profiler-server"]
