// Code generated by protoc-gen-go. DO NOT EDIT.

package proto

type Language int32

const (
	Language_PYTHON Language = 0
	Language_JAVA   Language = 1
	Language_GO     Language = 2
)

var Language_name = map[int32]string{
	0: "PYTHON",
	1: "JAVA",
	2: "GO",
}

var Language_value = map[string]int32{
	"PYTHON": 0,
	"JAVA":   1,
	"GO":     2,
}

func (x Language) String() string {
	return Language_name[int32(x)]
}

type ParameterSample struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ParameterSample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParameterSample) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ParameterSample) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ParameterSample) Reset()         { *x = ParameterSample{} }
func (x *ParameterSample) ProtoMessage() {}

type ProfileRequest struct {
	Language       Language           `protobuf:"varint,1,opt,name=language,proto3,enum=profiler.Language" json:"language,omitempty"`
	Code           string             `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	FunctionName   string             `protobuf:"bytes,3,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Parameters     []*ParameterSample `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty"`
	Tags           []string           `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	TimeoutSeconds int32              `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
}

func (x *ProfileRequest) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_PYTHON
}

func (x *ProfileRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProfileRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ProfileRequest) GetParameters() []*ParameterSample {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ProfileRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProfileRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ProfileRequest) Reset()         { *x = ProfileRequest{} }
func (x *ProfileRequest) ProtoMessage() {}

type PerformanceMetrics struct {
	CpuTimeMs       float64 `protobuf:"fixed64,1,opt,name=cpu_time_ms,json=cpuTimeMs,proto3" json:"cpu_time_ms,omitempty"`
	MemoryPeakMb    float64 `protobuf:"fixed64,2,opt,name=memory_peak_mb,json=memoryPeakMb,proto3" json:"memory_peak_mb,omitempty"`
	IoReadCount     int64   `protobuf:"varint,3,opt,name=io_read_count,json=ioReadCount,proto3" json:"io_read_count,omitempty"`
	IoWriteCount    int64   `protobuf:"varint,4,opt,name=io_write_count,json=ioWriteCount,proto3" json:"io_write_count,omitempty"`
	GcCount         int64   `protobuf:"varint,5,opt,name=gc_count,json=gcCount,proto3" json:"gc_count,omitempty"`
	GcTimeMs        float64 `protobuf:"fixed64,6,opt,name=gc_time_ms,json=gcTimeMs,proto3" json:"gc_time_ms,omitempty"`
	ExecutionTimeMs float64 `protobuf:"fixed64,7,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	Success         bool    `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string  `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *PerformanceMetrics) GetCpuTimeMs() float64 {
	if x != nil {
		return x.CpuTimeMs
	}
	return 0
}

func (x *PerformanceMetrics) GetMemoryPeakMb() float64 {
	if x != nil {
		return x.MemoryPeakMb
	}
	return 0
}

func (x *PerformanceMetrics) GetIoReadCount() int64 {
	if x != nil {
		return x.IoReadCount
	}
	return 0
}

func (x *PerformanceMetrics) GetIoWriteCount() int64 {
	if x != nil {
		return x.IoWriteCount
	}
	return 0
}

func (x *PerformanceMetrics) GetGcCount() int64 {
	if x != nil {
		return x.GcCount
	}
	return 0
}

func (x *PerformanceMetrics) GetGcTimeMs() float64 {
	if x != nil {
		return x.GcTimeMs
	}
	return 0
}

func (x *PerformanceMetrics) GetExecutionTimeMs() float64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *PerformanceMetrics) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PerformanceMetrics) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PerformanceMetrics) Reset()         { *x = PerformanceMetrics{} }
func (x *PerformanceMetrics) ProtoMessage() {}

type ProfileResponse struct {
	ProfileId    string             `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Metrics      *PerformanceMetrics `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	AssignedTags []string           `protobuf:"bytes,3,rep,name=assigned_tags,json=assignedTags,proto3" json:"assigned_tags,omitempty"`
}

func (x *ProfileResponse) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ProfileResponse) GetMetrics() *PerformanceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ProfileResponse) GetAssignedTags() []string {
	if x != nil {
		return x.AssignedTags
	}
	return nil
}

func (x *ProfileResponse) Reset()         { *x = ProfileResponse{} }
func (x *ProfileResponse) ProtoMessage() {}

type TagQuery struct {
	Tags     []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Operator string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
}

func (x *TagQuery) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TagQuery) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *TagQuery) Reset()         { *x = TagQuery{} }
func (x *TagQuery) ProtoMessage() {}

type ProfileQueryRequest struct {
	TagQuery      *TagQuery `protobuf:"bytes,1,opt,name=tag_query,json=tagQuery,proto3" json:"tag_query,omitempty"`
	StartTimeUnix int64     `protobuf:"varint,2,opt,name=start_time_unix,json=startTimeUnix,proto3" json:"start_time_unix,omitempty"`
	EndTimeUnix   int64     `protobuf:"varint,3,opt,name=end_time_unix,json=endTimeUnix,proto3" json:"end_time_unix,omitempty"`
	Limit         int32     `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ProfileQueryRequest) GetTagQuery() *TagQuery {
	if x != nil {
		return x.TagQuery
	}
	return nil
}

func (x *ProfileQueryRequest) GetStartTimeUnix() int64 {
	if x != nil {
		return x.StartTimeUnix
	}
	return 0
}

func (x *ProfileQueryRequest) GetEndTimeUnix() int64 {
	if x != nil {
		return x.EndTimeUnix
	}
	return 0
}

func (x *ProfileQueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ProfileQueryRequest) Reset()         { *x = ProfileQueryRequest{} }
func (x *ProfileQueryRequest) ProtoMessage() {}

type ProfileEntry struct {
	ProfileId     string             `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Language      Language           `protobuf:"varint,2,opt,name=language,proto3,enum=profiler.Language" json:"language,omitempty"`
	FunctionName  string             `protobuf:"bytes,3,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Metrics       *PerformanceMetrics `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Tags          []string           `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	TimestampUnix int64              `protobuf:"varint,6,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
}

func (x *ProfileEntry) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ProfileEntry) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_PYTHON
}

func (x *ProfileEntry) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ProfileEntry) GetMetrics() *PerformanceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ProfileEntry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProfileEntry) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *ProfileEntry) Reset()         { *x = ProfileEntry{} }
func (x *ProfileEntry) ProtoMessage() {}

type ProfileQueryResponse struct {
	Profiles   []*ProfileEntry `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	TotalCount int32           `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ProfileQueryResponse) GetProfiles() []*ProfileEntry {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *ProfileQueryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ProfileQueryResponse) Reset()         { *x = ProfileQueryResponse{} }
func (x *ProfileQueryResponse) ProtoMessage() {}
