// Code generated by protoc-gen-go. DO NOT EDIT.

package proto

type Language int32

const (
	Language_PYTHON Language = 0
	Language_JAVA   Language = 1
	Language_GO     Language = 2
)

var Language_name = map[int32]string{
	0: "PYTHON",
	1: "JAVA",
	2: "GO",
}

var Language_value = map[string]int32{
	"PYTHON": 0,
	"JAVA":   1,
	"GO":     2,
}

func (x Language) String() string {
	return Language_name[int32(x)]
}

type ParameterSample struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ParameterSample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParameterSample) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ParameterSample) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ParameterSample) Reset()         { *x = ParameterSample{} }
func (x *ParameterSample) ProtoMessage() {}

type ProfileRequest struct {
	Language       Language           `protobuf:"varint,1,opt,name=language,proto3,enum=profiler.Language" json:"language,omitempty"`
	Code           string             `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	FunctionName   string             `protobuf:"bytes,3,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Parameters     []*ParameterSample `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty"`
	Tags           []string           `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	TimeoutSeconds int32              `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
}

func (x *ProfileRequest) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_PYTHON
}

func (x *ProfileRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProfileRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ProfileRequest) GetParameters() []*ParameterSample {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ProfileRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProfileRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ProfileRequest) Reset()         { *x = ProfileRequest{} }
func (x *ProfileRequest) ProtoMessage() {}

type PerformanceMetrics struct {
	CpuTimeMs       float64 `protobuf:"fixed64,1,opt,name=cpu_time_ms,json=cpuTimeMs,proto3" json:"cpu_time_ms,omitempty"`
	MemoryPeakMb    float64 `protobuf:"fixed64,2,opt,name=memory_peak_mb,json=memoryPeakMb,proto3" json:"memory_peak_mb,omitempty"`
	IoReadCount     int64   `protobuf:"varint,3,opt,name=io_read_count,json=ioReadCount,proto3" json:"io_read_count,omitempty"`
	IoWriteCount    int64   `protobuf:"varint,4,opt,name=io_write_count,json=ioWriteCount,proto3" json:"io_write_count,omitempty"`
	GcCount         int64   `protobuf:"varint,5,opt,name=gc_count,json=gcCount,proto3" json:"gc_count,omitempty"`
	GcTimeMs        float64 `protobuf:"fixed64,6,opt,name=gc_time_ms,json=gcTimeMs,proto3" json:"gc_time_ms,omitempty"`
	ExecutionTimeMs float64 `protobuf:"fixed64,7,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	Success         bool    `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string  `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *PerformanceMetrics) GetCpuTimeMs() float64 {
	if x != nil {
		return x.CpuTimeMs
	}
	return 0
}

func (x *PerformanceMetrics) GetMemoryPeakMb() float64 {
	if x != nil {
		return x.MemoryPeakMb
	}
	return 0
}

func (x *PerformanceMetrics) GetIoReadCount() int64 {
	if x != nil {
		return x.IoReadCount
	}
	return 0
}

func (x *PerformanceMetrics) GetIoWriteCount() int64 {
	if x != nil {
		return x.IoWriteCount
	}
	return 0
}

func (x *PerformanceMetrics) GetGcCount() int64 {
	if x != nil {
		return x.GcCount
	}
	return 0
}

func (x *PerformanceMetrics) GetGcTimeMs() float64 {
	if x != nil {
		return x.GcTimeMs
	}
	return 0
}

func (x *PerformanceMetrics) GetExecutionTimeMs() float64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *PerformanceMetrics) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PerformanceMetrics) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PerformanceMetrics) Reset()         { *x = PerformanceMetrics{} }
func (x *PerformanceMetrics) ProtoMessage() {}

type ProfileResponse struct {
	ProfileId    string             `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Metrics      *PerformanceMetrics `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	AssignedTags []string           `protobuf:"bytes,3,rep,name=assigned_tags,json=assignedTags,proto3" json:"assigned_tags,omitempty"`
}

func (x *ProfileResponse) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ProfileResponse) GetMetrics() *PerformanceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ProfileResponse) GetAssignedTags() []string {
	if x != nil {
		return x.AssignedTags
	}
	return nil
}

func (x *ProfileResponse) Reset()         { *x = ProfileResponse{} }
func (x *ProfileResponse) ProtoMessage() {}

type TagQuery struct {
	Tags     []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Operator string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
}

func (x *TagQuery) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TagQuery) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *TagQuery) Reset()         { *x = TagQuery{} }
func (x *TagQuery) ProtoMessage() {}

type ProfileQueryRequest struct {
	TagQuery      *TagQuery `protobuf:"bytes,1,opt,name=tag_query,json=tagQuery,proto3" json:"tag_query,omitempty"`
	StartTimeUnix int64     `protobuf:"varint,2,opt,name=start_time_unix,json=startTimeUnix,proto3" json:"start_time_unix,omitempty"`
	EndTimeUnix   int64     `protobuf:"varint,3,opt,name=end_time_unix,json=endTimeUnix,proto3" json:"end_time_unix,omitempty"`
	Limit         int32     `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ProfileQueryRequest) GetTagQuery() *TagQuery {
	if x != nil {
		return x.TagQuery
	}
	return nil
}

func (x *ProfileQueryRequest) GetStartTimeUnix() int64 {
	if x != nil {
		return x.StartTimeUnix
	}
	return 0
}

func (x *ProfileQueryRequest) GetEndTimeUnix() int64 {
	if x != nil {
		return x.EndTimeUnix
	}
	return 0
}

func (x *ProfileQueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ProfileQueryRequest) Reset()         { *x = ProfileQueryRequest{} }
func (x *ProfileQueryRequest) ProtoMessage() {}

type ProfileEntry struct {
	ProfileId     string             `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Language      Language           `protobuf:"varint,2,opt,name=language,proto3,enum=profiler.Language" json:"language,omitempty"`
	FunctionName  string             `protobuf:"bytes,3,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Metrics       *PerformanceMetrics `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Tags          []string           `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	TimestampUnix int64              `protobuf:"varint,6,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
}

func (x *ProfileEntry) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ProfileEntry) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_PYTHON
}

func (x *ProfileEntry) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ProfileEntry) GetMetrics() *PerformanceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ProfileEntry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProfileEntry) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *ProfileEntry) Reset()         { *x = ProfileEntry{} }
func (x *ProfileEntry) ProtoMessage() {}

type ProfileQueryResponse struct {
	Profiles   []*ProfileEntry `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	TotalCount int32           `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ProfileQueryResponse) GetProfiles() []*ProfileEntry {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *ProfileQueryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ProfileQueryResponse) Reset()         { *x = ProfileQueryResponse{} }
func (x *ProfileQueryResponse) ProtoMessage() {}

type MetricDiff struct {
	MetricName     string  `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	OldValue       float64 `protobuf:"fixed64,2,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue       float64 `protobuf:"fixed64,3,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	AbsoluteDiff   float64 `protobuf:"fixed64,4,opt,name=absolute_diff,json=absoluteDiff,proto3" json:"absolute_diff,omitempty"`
	PercentageDiff float64 `protobuf:"fixed64,5,opt,name=percentage_diff,json=percentageDiff,proto3" json:"percentage_diff,omitempty"`
	ChangeType     string  `protobuf:"bytes,6,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	IsSignificant  bool    `protobuf:"varint,7,opt,name=is_significant,json=isSignificant,proto3" json:"is_significant,omitempty"`
}

func (x *MetricDiff) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *MetricDiff) GetOldValue() float64 {
	if x != nil {
		return x.OldValue
	}
	return 0
}

func (x *MetricDiff) GetNewValue() float64 {
	if x != nil {
		return x.NewValue
	}
	return 0
}

func (x *MetricDiff) GetAbsoluteDiff() float64 {
	if x != nil {
		return x.AbsoluteDiff
	}
	return 0
}

func (x *MetricDiff) GetPercentageDiff() float64 {
	if x != nil {
		return x.PercentageDiff
	}
	return 0
}

func (x *MetricDiff) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *MetricDiff) GetIsSignificant() bool {
	if x != nil {
		return x.IsSignificant
	}
	return false
}

func (x *MetricDiff) Reset()         { *x = MetricDiff{} }
func (x *MetricDiff) ProtoMessage() {}

type SourceLineDiff struct {
	LineNumber           int32   `protobuf:"varint,1,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	OldLine              string  `protobuf:"bytes,2,opt,name=old_line,json=oldLine,proto3" json:"old_line,omitempty"`
	NewLine              string  `protobuf:"bytes,3,opt,name=new_line,json=newLine,proto3" json:"new_line,omitempty"`
	LineType             string  `protobuf:"bytes,4,opt,name=line_type,json=lineType,proto3" json:"line_type,omitempty"`
	DiffHint             string  `protobuf:"bytes,5,opt,name=diff_hint,json=diffHint,proto3" json:"diff_hint,omitempty"`
	PerformanceImpactScore float64 `protobuf:"fixed64,6,opt,name=performance_impact_score,json=performanceImpactScore,proto3" json:"performance_impact_score,omitempty"`
}

func (x *SourceLineDiff) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *SourceLineDiff) GetOldLine() string {
	if x != nil {
		return x.OldLine
	}
	return ""
}

func (x *SourceLineDiff) GetNewLine() string {
	if x != nil {
		return x.NewLine
	}
	return ""
}

func (x *SourceLineDiff) GetLineType() string {
	if x != nil {
		return x.LineType
	}
	return ""
}

func (x *SourceLineDiff) GetDiffHint() string {
	if x != nil {
		return x.DiffHint
	}
	return ""
}

func (x *SourceLineDiff) GetPerformanceImpactScore() float64 {
	if x != nil {
		return x.PerformanceImpactScore
	}
	return 0
}

func (x *SourceLineDiff) Reset()         { *x = SourceLineDiff{} }
func (x *SourceLineDiff) ProtoMessage() {}

type CompareProfilesRequest struct {
	OldProfileId         string  `protobuf:"bytes,1,opt,name=old_profile_id,json=oldProfileId,proto3" json:"old_profile_id,omitempty"`
	NewProfileId         string  `protobuf:"bytes,2,opt,name=new_profile_id,json=newProfileId,proto3" json:"new_profile_id,omitempty"`
	OldSourceCode        string  `protobuf:"bytes,3,opt,name=old_source_code,json=oldSourceCode,proto3" json:"old_source_code,omitempty"`
	NewSourceCode        string  `protobuf:"bytes,4,opt,name=new_source_code,json=newSourceCode,proto3" json:"new_source_code,omitempty"`
	SignificanceThreshold float64 `protobuf:"fixed64,5,opt,name=significance_threshold,json=significanceThreshold,proto3" json:"significance_threshold,omitempty"`
}

func (x *CompareProfilesRequest) GetOldProfileId() string {
	if x != nil {
		return x.OldProfileId
	}
	return ""
}

func (x *CompareProfilesRequest) GetNewProfileId() string {
	if x != nil {
		return x.NewProfileId
	}
	return ""
}

func (x *CompareProfilesRequest) GetOldSourceCode() string {
	if x != nil {
		return x.OldSourceCode
	}
	return ""
}

func (x *CompareProfilesRequest) GetNewSourceCode() string {
	if x != nil {
		return x.NewSourceCode
	}
	return ""
}

func (x *CompareProfilesRequest) GetSignificanceThreshold() float64 {
	if x != nil {
		return x.SignificanceThreshold
	}
	return 0
}

func (x *CompareProfilesRequest) Reset()         { *x = CompareProfilesRequest{} }
func (x *CompareProfilesRequest) ProtoMessage() {}

type CompareProfilesResponse struct {
	OldProfileId   string           `protobuf:"bytes,1,opt,name=old_profile_id,json=oldProfileId,proto3" json:"old_profile_id,omitempty"`
	NewProfileId   string           `protobuf:"bytes,2,opt,name=new_profile_id,json=newProfileId,proto3" json:"new_profile_id,omitempty"`
	TimeDeltaSeconds int64          `protobuf:"varint,3,opt,name=time_delta_seconds,json=timeDeltaSeconds,proto3" json:"time_delta_seconds,omitempty"`
	MetricDiffs    []*MetricDiff    `protobuf:"bytes,4,rep,name=metric_diffs,json=metricDiffs,proto3" json:"metric_diffs,omitempty"`
	OverallSummary string           `protobuf:"bytes,5,opt,name=overall_summary,json=overallSummary,proto3" json:"overall_summary,omitempty"`
	PerformanceTrend string         `protobuf:"bytes,6,opt,name=performance_trend,json=performanceTrend,proto3" json:"performance_trend,omitempty"`
	SourceDiffs    []*SourceLineDiff `protobuf:"bytes,7,rep,name=source_diffs,json=sourceDiffs,proto3" json:"source_diffs,omitempty"`
	RegressionTags []string         `protobuf:"bytes,8,rep,name=regression_tags,json=regressionTags,proto3" json:"regression_tags,omitempty"`
	ImprovementTags []string        `protobuf:"bytes,9,rep,name=improvement_tags,json=improvementTags,proto3" json:"improvement_tags,omitempty"`
}

func (x *CompareProfilesResponse) GetOldProfileId() string {
	if x != nil {
		return x.OldProfileId
	}
	return ""
}

func (x *CompareProfilesResponse) GetNewProfileId() string {
	if x != nil {
		return x.NewProfileId
	}
	return ""
}

func (x *CompareProfilesResponse) GetTimeDeltaSeconds() int64 {
	if x != nil {
		return x.TimeDeltaSeconds
	}
	return 0
}

func (x *CompareProfilesResponse) GetMetricDiffs() []*MetricDiff {
	if x != nil {
		return x.MetricDiffs
	}
	return nil
}

func (x *CompareProfilesResponse) GetOverallSummary() string {
	if x != nil {
		return x.OverallSummary
	}
	return ""
}

func (x *CompareProfilesResponse) GetPerformanceTrend() string {
	if x != nil {
		return x.PerformanceTrend
	}
	return ""
}

func (x *CompareProfilesResponse) GetSourceDiffs() []*SourceLineDiff {
	if x != nil {
		return x.SourceDiffs
	}
	return nil
}

func (x *CompareProfilesResponse) GetRegressionTags() []string {
	if x != nil {
		return x.RegressionTags
	}
	return nil
}

func (x *CompareProfilesResponse) GetImprovementTags() []string {
	if x != nil {
		return x.ImprovementTags
	}
	return nil
}

func (x *CompareProfilesResponse) Reset()         { *x = CompareProfilesResponse{} }
func (x *CompareProfilesResponse) ProtoMessage() {}
