// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// source: proto/profiler.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PerformanceProfilerClient is the client API for PerformanceProfiler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PerformanceProfilerClient interface {
	ProfileCode(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	QueryProfiles(ctx context.Context, in *ProfileQueryRequest, opts ...grpc.CallOption) (*ProfileQueryResponse, error)
}

type performanceProfilerClient struct {
	cc grpc.ClientConnInterface
}

func NewPerformanceProfilerClient(cc grpc.ClientConnInterface) PerformanceProfilerClient {
	return &performanceProfilerClient{cc}
}

func (c *performanceProfilerClient) ProfileCode(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/profiler.PerformanceProfiler/ProfileCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceProfilerClient) QueryProfiles(ctx context.Context, in *ProfileQueryRequest, opts ...grpc.CallOption) (*ProfileQueryResponse, error) {
	out := new(ProfileQueryResponse)
	err := c.cc.Invoke(ctx, "/profiler.PerformanceProfiler/QueryProfiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PerformanceProfilerServer is the server API for PerformanceProfiler service.
// All implementations must embed UnimplementedPerformanceProfilerServer
// for forward compatibility
type PerformanceProfilerServer interface {
	ProfileCode(context.Context, *ProfileRequest) (*ProfileResponse, error)
	QueryProfiles(context.Context, *ProfileQueryRequest) (*ProfileQueryResponse, error)
	mustEmbedUnimplementedPerformanceProfilerServer()
}

// UnimplementedPerformanceProfilerServer must be embedded to have forward compatible implementations.
type UnimplementedPerformanceProfilerServer struct {
}

func (UnimplementedPerformanceProfilerServer) ProfileCode(context.Context, *ProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProfileCode not implemented")
}
func (UnimplementedPerformanceProfilerServer) QueryProfiles(context.Context, *ProfileQueryRequest) (*ProfileQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryProfiles not implemented")
}
func (UnimplementedPerformanceProfilerServer) mustEmbedUnimplementedPerformanceProfilerServer() {}

// UnsafePerformanceProfilerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PerformanceProfilerServer will
// result in compilation errors.
type UnsafePerformanceProfilerServer interface {
	mustEmbedUnimplementedPerformanceProfilerServer()
}

func RegisterPerformanceProfilerServer(s grpc.ServiceRegistrar, srv PerformanceProfilerServer) {
	s.RegisterService(&PerformanceProfiler_ServiceDesc, srv)
}

func _PerformanceProfiler_ProfileCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceProfilerServer).ProfileCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profiler.PerformanceProfiler/ProfileCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceProfilerServer).ProfileCode(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceProfiler_QueryProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceProfilerServer).QueryProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profiler.PerformanceProfiler/QueryProfiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceProfilerServer).QueryProfiles(ctx, req.(*ProfileQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PerformanceProfiler_ServiceDesc is the grpc.ServiceDesc for PerformanceProfiler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PerformanceProfiler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profiler.PerformanceProfiler",
	HandlerType: (*PerformanceProfilerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProfileCode",
			Handler:    _PerformanceProfiler_ProfileCode_Handler,
		},
		{
			MethodName: "QueryProfiles",
			Handler:    _PerformanceProfiler_QueryProfiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/profiler.proto",
}
